/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AVRFlasherGUI.java
 *
 * Created on 19.05.2011, 10:19:42
 */
package gui;
import java.io.*;
import gnu.io.*;
import java.lang.*;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import crc.*;
import uart.*;
import type.*;

/**
 *
 * @author Huebener.Se
 */
public class AVRFlasherGUI extends javax.swing.JFrame {

	/** Creates new form AVRFlasherGUI */
	public AVRFlasherGUI() {
		initComponents();
		               
		cbox_AvailablePorts.removeAllItems();
		RS232.updateAvailablePorts();
		for(AvailablePorts_t port : RS232.Ports) {
			cbox_AvailablePorts.addItem(port.PortName);
		}	                
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_logwindow = new javax.swing.JTextArea();
        btn_selectexfile = new javax.swing.JButton();
        txt_selectedfile = new javax.swing.JTextField();
        btn_loadfile = new javax.swing.JButton();
        btn_ReloadPorts = new javax.swing.JButton();
        lbl_AvailablePorts = new javax.swing.JLabel();
        cbox_AvailablePorts = new javax.swing.JComboBox();
        lbl_BaudRate = new javax.swing.JLabel();
        cbox_BaudRate = new javax.swing.JComboBox();
        btn_Connect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("openDrive AVRFlasher");
        setName("frm_main"); // NOI18N

        txt_logwindow.setColumns(20);
        txt_logwindow.setRows(5);
        jScrollPane1.setViewportView(txt_logwindow);

        btn_selectexfile.setText("Select .hex File");
        btn_selectexfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectexfileActionPerformed(evt);
            }
        });

        txt_selectedfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_selectedfileActionPerformed(evt);
            }
        });

        btn_loadfile.setText("Load");
        btn_loadfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadfileActionPerformed(evt);
            }
        });

        btn_ReloadPorts.setText("Reload");
        btn_ReloadPorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReloadPortsActionPerformed(evt);
            }
        });

        lbl_AvailablePorts.setText("Port:");

        cbox_AvailablePorts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_AvailablePortsActionPerformed(evt);
            }
        });

        lbl_BaudRate.setText("BaudRate:");

        cbox_BaudRate.setEditable(true);
        cbox_BaudRate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "300", "600", "1200", "2400", "4800", "9600", "14400", "19200", "28800", "38400", "56000", "57600", "115200", "128000", "256000", "921600", "1000000", "1500000", "2000000" }));

        btn_Connect.setText("Connect");
        btn_Connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_selectedfile, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_selectexfile))
                    .addComponent(btn_loadfile, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_AvailablePorts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_AvailablePorts, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ReloadPorts)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_BaudRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btn_Connect)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbox_AvailablePorts, cbox_BaudRate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Connect, btn_selectexfile});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_AvailablePorts)
                    .addComponent(cbox_AvailablePorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ReloadPorts)
                    .addComponent(lbl_BaudRate)
                    .addComponent(cbox_BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Connect))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_selectedfile, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selectexfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_loadfile)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_selectexfile, txt_selectedfile});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_ReloadPorts, cbox_AvailablePorts, cbox_BaudRate, lbl_AvailablePorts});

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btn_selectexfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectexfileActionPerformed
		
		
		final JFileChooser fc = new JFileChooser();
		fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
		fc.setMultiSelectionEnabled(false);
		fc.setDialogTitle("Choose a file");
				
		fc.setAcceptAllFileFilterUsed(false);
		fc.addChoosableFileFilter(new FileNameExtensionFilter("Text-Files (*.txt)", "txt"));
		fc.addChoosableFileFilter(new FileNameExtensionFilter("Intel-Hex-Files (*.hex)", "hex"));

		fc.setCurrentDirectory(new File("C:/Users/Huebener.Se/Desktop/openDrive/handbox-eq6/Bootloader-TestProgram/Debug"));		
		
		
        if (fc.showOpenDialog(AVRFlasherGUI.this) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
			txt_selectedfile.setText(file.toString());
        }
		
		return;
	}//GEN-LAST:event_btn_selectexfileActionPerformed

	private void txt_selectedfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_selectedfileActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txt_selectedfileActionPerformed

	private void btn_loadfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadfileActionPerformed

								
		try {
			FileReader fr = new FileReader(txt_selectedfile.getText());
			BufferedReader br = new BufferedReader(fr);
			CRC16 c = new CRC16();
			txt_logwindow.setText("");

			while(true) {
				String line = br.readLine();
				if(line == null) {break;}
				
				
				c.reset();
				c.calc_crc16(line);
                                
				txt_logwindow.setText(txt_logwindow.getText() + line +" -> 0x"+ misc.Int2HexString(c.value) +"\n");
				System.out.println(line +" -> 0x"+ misc.Int2HexString(c.value));				
			}
			br.close();
			


		} catch(Exception e) {}				
		
	}//GEN-LAST:event_btn_loadfileActionPerformed

	private void btn_ReloadPortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReloadPortsActionPerformed
		
		cbox_AvailablePorts.removeAllItems();
		RS232.updateAvailablePorts();
		for(AvailablePorts_t port : RS232.Ports) {
			cbox_AvailablePorts.addItem(port.PortName);
		}
		
	}//GEN-LAST:event_btn_ReloadPortsActionPerformed

	private void cbox_AvailablePortsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_AvailablePortsActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_cbox_AvailablePortsActionPerformed

	private void btn_ConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConnectActionPerformed
		
		String sPortName = cbox_AvailablePorts.getSelectedItem().toString();
		int sPortBaudrate = Integer.valueOf(cbox_BaudRate.getSelectedItem().toString());
		
		if(!RS232.isConnected(sPortName)) {
			//Not connected -> connect now!
		
			RS232.setSettings(sPortName, sPortBaudrate, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);				
			if(RS232.Connect(sPortName)) {
				btn_Connect.setText("Disconnect");
			}
		} else {
			//Connected -> disconnect!
			RS232.CloseConnection(sPortName);
			btn_Connect.setText("Connect");
		}
	}//GEN-LAST:event_btn_ConnectActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new AVRFlasherGUI().setVisible(true);
			}
		});
	}

	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Connect;
    private javax.swing.JButton btn_ReloadPorts;
    private javax.swing.JButton btn_loadfile;
    private javax.swing.JButton btn_selectexfile;
    private javax.swing.JComboBox cbox_AvailablePorts;
    private javax.swing.JComboBox cbox_BaudRate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_AvailablePorts;
    private javax.swing.JLabel lbl_BaudRate;
    private javax.swing.JTextArea txt_logwindow;
    private javax.swing.JTextField txt_selectedfile;
    // End of variables declaration//GEN-END:variables
}
